Changes #33 Delete nurse by id(CRUD)
Cri4tura/Hospital-Back-end pull request #51
Opened 2024-11-06 15:03 UTC by marchyxd

2024-11-06 15:05 UTC, Cri4tura requested changes
que no sea un verbo

2024-11-06 15:09 UTC, Ashla-StarWars approved these changes
Cuidado con el formato del codigo. por lo demas muy bien

2024-11-06 15:10 UTC, Cri4tura submitted a review, later dismissed
ok

2024-11-07 14:49 UTC, Cri4tura approved these changes
ok

2024-11-07 14:52 UTC, Ashla-StarWars approved these changes
reapproved 👯

2024-11-07 14:52 UTC, merged